DROP DATABASE IF EXISTS patientdb;
DROP USER IF EXISTS `patientadmin`@`%`;
CREATE DATABASE IF NOT EXISTS patientdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `patientadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'Password1!';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `patientdb`.* TO `patientadmin`@`%`;
