spring.application.name=patient-service

#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:patientdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=oluwafemi
#spring.datasource.password=Floating1!
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#spring.jpa.open-in-view=true
server.port=8084

##For SpringSecurity OAuth2 Resource Server JWT Issuer URI
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth2-server:9000

#For Actuator Health Probes
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true

#For Swagger
springdoc.swagger-ui.disable-swagger-default-url=false
logging.level.root=info

#For MySql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-and-create.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.open-in-view=false
#Kafak Apache
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer