spring.application.name=patient-service

spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:patientdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=oluwafemi
spring.datasource.password=Floating1!

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.open-in-view=true
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true

logging.level.root=info
